package blora.localization

import kotlinx.serialization.Serializable
import net.kyori.adventure.text.minimessage.tag.resolver.TagResolver

@Serializable
data class CommandLocalizationContents(
    val commandErrorPlayer_only: String = "只有玩家才可以执行该命令",
    val commandErrorBlock_only: String = "只有方块才可以执行该命令",
    val commandErrorNo_suitable_executor: String = "无法运行该命令",
    val commandMailSuccessDelete_mail: String = "成功删除系统邮件 <id>",
    val commandMailErrorSystem_mail_not_exists: String = "ID 为 <id> 的系统邮件不存在",
    val commandMailErrorPlayer_received_mail: String = "玩家 <player> 已经收到了 ID 为 <id> 的系统邮件",
    val commandReloadSuccessSynced: String = "<green>配置与语言文件已重载，并已同步至代理与其他服务器",
    val commandReloadSuccessLocal_only: String = "<yellow>本服配置与语言文件已重载（未连接代理，未同步其他服务器）",
)

@Serializable
data class MailLocalizationContents(
    val mailClaim_attachment: String = "已领取邮件的附件",
    val mailErrorClaimInventory_not_enought: String = "<red>背包空间不足，无法领取",
    val mailErrorClaimNot_claimable_in_this_server: String = "<red>当前邮件存在无法在目前服务器领取的附件",
    val mailNotify: String = "您收到了一份新的邮件！<yellow>[点击查看]",
    val mailNotifyHover: String = "<title><newline><newline><bold>发件人：</bold><sender>",
    val mailJoinUnreadTips: String = "您有 <amount> 份未读邮件！<yellow>[点击查看]",
    val mailJoinUnreadTipsHover: String = "点击打开邮箱",
    val mailSenderUnknown: String = "未知发送者",
    val mailSenderSystemDefault: String = "<bold>系统",
    val mailTooltipView: String = "<blora:color:success>查看邮件",
    val mailTooltipSender: String = "<bold>发送者：<sender>",
    val mailTooltipSendingDate: String = "<bold>显示的发送日期：<date>",
    val mailTooltipCreatedAt: String = "<bold>创建于：<date>",
    val mailTooltipCreator: String = "<bold>创建者：<creator>",
    val mailSystemTooltipTrigger: String = "<bold>触发器：",
    val mailSystemTooltipTriggerOnline_in_range: String = "- 于 <from> 至 <to> 期间上线过触发",
    val mailSystemTooltipTriggerOnline_before: String = "- 于 <date> 前上线过触发",
    val mailSystemTooltipTriggerOnline_in_recent_days: String = "- 于 <date> 的 <days> 天前之内上线过触发",
    val mailSystemTooltipTriggerOnline_in_recent_days_0: String = "- 于 <date> 的当天上线过触发",
    val mailSystemTooltipStatus: String = "<bold>状态：<status>",
    val mailSystemTooltipStatusActivated: String = "已激活",
    val mailSystemTooltipStatusInactivated: String = "未激活",
    val mailTooltipManagementLeft_click: String = "<blora:color:success>左键点击预览",
    val mailTooltipManagementRight_click: String = "<blora:color:error>右键点击切换开启状态",
    val mailViewSender: String = "<bold>发件人：<bold:false><italic><sender>",
    val mailViewTime: String = "<bold>发送时间：<bold:false><italic><date>",
    val mailViewContents: String = "<bold>内容：",
    val mailViewAttachment: String = "<bold>附件：",
    val mailViewAttachment_claimed: String = "<bold>附件（已领取）：",
    val mailErrorNo_permission_to_create_system_mail: String = "你没有创建系统邮件的权限",
    val mailWarningTitle_cannot_be_empty: String = "标题不能为空",
    val mailSuccessCreate_system_mail: String = "成功创建系统邮件 <mail_id>",
    val dialogCreate_system_mailInputTitle: String = "邮件标题",
    val dialogCreate_system_mailInputSystem_sender: String = "系统发件人名称（可选）",
    val dialogCreate_system_mailInputContents: String = "邮件内容",
    val dialogCreate_system_mailButtonCreate: String = "创建",
    val dialogCreate_system_mailButtonCancel: String = "取消",
    val dialogModify_titleTitle: String = "修改邮件标题",
    val dialogModify_system_senderTitle: String = "修改邮件标题",
    val dialogModify_contentsTitle: String = "修改邮件内容",
    val dialogModify_titleInputPlaceholderTitle: String = "标题内容",
    val dialogModify_system_senderInputPlaceholderSystem_sender: String = "系统发送者名称",
    val dialogModify_contentsInputPlaceholderContents: String = "邮件内容",
    val dialogModify_dateModify_online_before_triggerTitle: String = "编辑日期",
    val dialogModify_dateInputPlaceholderYear: String = "年份",
    val dialogModify_dateInputPlaceholderMonth: String = "月份",
    val dialogModify_dateInputPlaceholderDay: String = "日期",
    val dialogModify_datetimeModify_receive_dateTitle: String = "编辑日期",
    val dialogModify_datetimeInputPlaceholderHour: String = "时",
    val dialogModify_datetimeInputPlaceholderMinute: String = "分",
    val dialogModify_datetimeInputPlaceholderSecond: String = "秒",
    val dialogModify_dateWarningYear_must_be_no_negative_digital: String = "年份必须是一个符号为正的<bold>整数<reset>!",
    val dialogModify_dateWarningDay_out_of_limit: String = "日期超过了 <month> 月在 <year> 年的最大天数",
    val dialogModify_daysTitle: String = "修改天数",
    val dialogModify_daysInputPlaceholderDays: String = "天数",
    val dialogModify_amountTitle: String = "修改数量",
    val dialogModify_amountInputPlaceholderAmount: String = "数量",
    val dialogModify_amountWarningMust_be_uint: String = "数量必须是一个正整数",
    val dialogSet_system_mail_identifierTitle: String = "设置邮件 ID",
    val dialogSet_system_mail_identifierWarningIdentifier_exists: String = "当前 ID 已被使用",
    val dialogSet_system_mail_identifierWarningIdentifier_illegal: String = "ID 必须符合如下正则：[a-zA-Z][a-zA-Z0-9_]*",
    val dialogSet_system_mail_identifierInputPlaceholderIdentifier: String = "ID",
    val menuSystem_mail_managementTitle: String = "系统邮件管理",
    val menuMail_listTitle: String = "邮件列表",
    val menuMail_listButtonClaim: String = "领取附件",
    val menuMail_listButtonBack: String = "返回",
    val menuCreate_system_mailTitle: String = "创建系统邮件",
    val menuCreate_system_mailWarningTitle_cannot_be_empty: String = "标题不能为空",
    val menuCreate_system_mailButtonModify_title: String = "修改邮件标题",
    val menuCreate_system_mailButtonModify_system_sender: String = "修改系统发件人名称",
    val menuCreate_system_mailButtonModify_contents: String = "修改邮件内容",
    val menuCreate_system_mailButtonModify_trigger: String = "修改邮件触发器",
    val menuCreate_system_mailButtonModify_attachment: String = "修改邮件附件",
    val menuCreate_system_mailButtonModify_date: String = "修改邮件显示日期",
    val menuCreate_system_mailButtonModify_dateDescriptionNot_set: String = "<italic:false><white>未指定",
    val menuCreate_system_mailButtonModify_dateDescriptionTooltip1: String = "<italic:false><blora:color:success>左键点击修改",
    val menuCreate_system_mailButtonModify_dateDescriptionTooltip2: String = "<italic:false><blora:color:error>右键点击删除",
    val menuCreate_system_mailButtonCreate: String = "创建系统邮件",
    val menuCreate_system_mailPageModify_triggersTitle: String = "修改邮件触发器",
    val menuCreate_system_mailPageModify_triggersButtonDescriptionNot_set: String = "<italic:false><white>未启用该触发器",
    val menuCreate_system_mailPageModify_triggersButtonOnline_before: String = "在指定日期前登录",
    val menuCreate_system_mailPageModify_triggersButtonOnline_beforeDescription: String = "于 <date> 前上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_range: String = "在指定日期区间内登录",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_rangeDescription: String = "于 <from> 至 <to> 期间上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_days: String = "在指定天数内上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_daysDescription: String = "于 <date> 的 <days> 天前之内上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_daysDescription_0days: String = "于 <date> 的当天上线过触发",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeTitle: String = "在指定日期区间内登录",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeButtonModify_from: String = "修改开始日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeButtonModify_to: String = "修改结束日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeWarningFrom_later_than_to: String = "开始日期不能比结束日期更晚",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysTitle: String = "在指定天数内上线过触发",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_anchor: String = "修改锚定日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_days: String = "修改天数",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_daysDescription: String = "<italic:false><white><days> 天",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysWarningDays_must_be_non_negative: String = "天数必须是非负整数",
    val menuCreate_system_mailPageModify_attachmentTitle: String = "修改附件",
    val menuCreate_system_mailPageModify_attachmentItemTitle: String = "<italic:false><white>数量 x<amount>",
    val menuCreate_system_mailPageModify_attachmentItemTooltip1: String = "<italic:false><white><bold>名称：",
    val menuCreate_system_mailPageModify_attachmentItemTooltip2: String = "<italic:false><white><bold>描述：",
    val menuCreate_system_mailPageModify_attachmentItemDescription1: String = "<italic:false><blora:color:success>左键点击修改数量",
    val menuCreate_system_mailPageModify_attachmentItemDescription2: String = "<italic:false><blora:color:error>右键点击删除",
    val menuCreate_system_mailPageModify_attachmentCoinTitle: String = "金币",
    val menuCreate_system_mailPageModify_attachmentBloriusTitle: String = "络琅",
    val menuCreate_system_mailPageModify_attachmentCoin_and_bloriusTooltip: String = "<italic:false><white>数量：<amount>",
    val menuCreate_system_mailPageModify_attachmentCoin_and_bloriusDescription2: String = "<italic:false><blora:color:error>右键点击归零",
)

@Serializable
data class RedeemLocalizationContents(
    val redeemNotExists: String = "兑换码不存在",
    val redeemCreate: String = "成功创建兑换码 <redeem>",
    val redeemSuccess: String = "成功兑换兑换码 <redeem>，请前往邮箱查看",
    val redeemMailTitle: String = "兑换码奖励",
    val redeemMailSender: String = "百络谷",
    val redeemMailContents: String = "兑换码 <redeem> 的奖励，请注意查收。",
    val redeemTooltipManagementLeft_click: String = "<blora:color:success>左键查看附件",
    val redeemTooltipManagementRight_click: String = "<blora:color:error>右键删除",
    val dialogCreate_redeemTitle: String = "创建兑换码",
    val dialogCreate_redeemWarningExists: String = "兑换码已存在",
    val dialogCreate_redeemWarningName_illegal: String = "兑换码应该只包含字母和数字！（不区分大小写）",
    val dialogCreate_redeemInputPlaceholderRedeem: String = "兑换码",
    val dialogCreate_redeemInputPlaceholderOne_use: String = "是否为一次性兑换码",
    val dialogRedeemTitle: String = "使用兑换码",
    val dialogRedeemWarningNot_exists: String = "兑换码不存在",
    val dialogRedeemWarningRedeemed: String = "您已兑换过该兑换码了",
    val dialogRedeemWarningUsed: String = "该兑换码已被使用",
    val dialogRedeemInputPlaceholderRedeem: String = "兑换码",
    val menuRedeem_code_managementTitle: String = "兑换码管理",
    val menuRedeem_code_managementItemTooltipCreator: String = "<bold>创建者：<creator>",
    val menuRedeem_code_managementItemTooltipCreated_at: String = "<bold>创建于：<date>",
    val menuRedeem_code_managementButtonAdd_new: String = "添加兑换码",
)

@Serializable
data class LeaderboardLocalizationContents(
    val coinsPrefix: String = "========== 金币排行榜 ==========",
    val coinsContent: String = "#<rank> <player> - <coins> 金币",
    val coinsSuffix: String = "==============================",
    val bloriusPrefix: String = "========== 络琅排行榜 ==========",
    val bloriusContent: String = "#<rank> <player> - <blorius> 络琅",
    val bloriusSuffix: String = "==============================",
    val levelsPrefix: String = "========== 等级排行榜 ==========",
    val levelsContent: String = "#<rank> <player> - <level> 级 (共 <exp> 经验)",
    val levelsSuffix: String = "==============================",
)

@Serializable
data class LocalizationContents(
    val command: CommandLocalizationContents = CommandLocalizationContents(),
    val mail: MailLocalizationContents = MailLocalizationContents(),
    val redeem: RedeemLocalizationContents = RedeemLocalizationContents(),
    val leaderboard: LeaderboardLocalizationContents = LeaderboardLocalizationContents(),
    val menuErrorTitle: String = "出现错误，请点击中间的按钮返回上一页",
    val chatMentionTitle: String = "有人在聊天中 @ 了您",
    val chatViewInventory: String = "<viewee> 的背包",
    val chatViewEnderChest: String = "<viewee> 的末影箱",
    val chatViewInventoryTooltip: String = "点击查看",
    val chatViewEnderChestTooltip: String = "点击查看",
    val chatViewSnapshotExpired: String = "<#f38ba8>该展示已过期，无法查看。",
    val chatErrorMuted: String = "您已经被禁言",
    val dialogInputBooleanYes: String = "是",
    val dialogInputBooleanNo: String = "否",
    val dialogButtonConfirm: String = "确认",
    val dialogButtonCancel: String = "取消",
    val menuButtonConfirm: String = "确认",
    val menuButtonCancel: String = "取消",
    val menuButtonBack: String = "返回",
    val menuButtonPrevious_page: String = "上一页",
    val menuButtonNext_page: String = "下一页",
    val customPlaceholders: Map<String, String> = mapOf(
        "commandPrefix" to "<dark_gray>[<blora:color:commandPrefix>命令<dark_gray>]<reset> ",
        "managementPrefix" to "<dark_gray>[<blora:color:managementPrefix>管理<dark_gray>]<reset> ",
    ),
    val customColors: Map<String, String> = mapOf(
        "success" to "211, 218, 196",
        "error" to "156, 88, 62",
        "commandPrefix" to "156, 169, 134",
        "managementPrefix" to "171, 170, 120",
        "primary" to "187, 184, 185",
        "primaryHighlight" to "225, 218, 211"
    ),
) {

    fun resolver(): TagResolver {
        return LocalizationsTagResolver(
            this.customPlaceholders.toMap(),
            this.customColors.toMap()
        )
    }

}
