package blora.localization

import kotlinx.serialization.Serializable
import net.kyori.adventure.text.minimessage.tag.resolver.TagResolver

@Serializable
data class CommandLocalizationContents(
    val commandErrorPlayer_only: String = "只有玩家才可以执行该命令",
    val commandErrorBlock_only: String = "只有方块才可以执行该命令",
    val commandErrorNo_suitable_executor: String = "无法运行该命令",
    val commandMailSuccessDelete_mail: String = "成功删除系统邮件 <id>",
    val commandMailErrorSystem_mail_not_exists: String = "ID 为 <id> 的系统邮件不存在",
    val commandMailErrorPlayer_received_mail: String = "玩家 <player> 已经收到了 ID 为 <id> 的系统邮件",
)

@Serializable
data class MailLocalizationContents(
    val mailClaim_attachment: String = "已领取邮件的附件",
    val mailErrorClaimInventory_not_enought: String = "<red>背包空间不足，无法领取",
    val mailErrorClaimNot_claimable_in_this_server: String = "<red>当前邮件存在无法在目前服务器领取的附件",
    val mailNotify: String = "您收到了一份新的邮件！<yellow>[点击查看]",
    val mailNotifyHover: String = "<title><newline><newline><bold>发件人：</bold><sender>",
    val mailJoinUnreadTips: String = "您有 <amount> 份未读邮件！<yellow>[点击查看]",
    val mailJoinUnreadTipsHover: String = "点击打开邮箱",
    val mailSenderUnknown: String = "未知发送者",
    val mailSenderSystemDefault: String = "<bold>系统",
    val mailTooltipView: String = "<blora:color:success>查看邮件",
    val mailTooltipSender: String = "<bold>发送者：<sender>",
    val mailTooltipSendingDate: String = "<bold>显示的发送日期：<date>",
    val mailTooltipCreatedAt: String = "<bold>创建于：<date>",
    val mailTooltipCreator: String = "<bold>创建者：<creator>",
    val mailSystemTooltipTrigger: String = "<bold>触发器：",
    val mailSystemTooltipTriggerOnline_in_range: String = "- 于 <from> 至 <to> 期间上线过触发",
    val mailSystemTooltipTriggerOnline_before: String = "- 于 <date> 前上线过触发",
    val mailSystemTooltipTriggerOnline_in_recent_days: String = "- 于 <date> 的 <days> 天前之内上线过触发",
    val mailSystemTooltipTriggerOnline_in_recent_days_0: String = "- 于 <date> 的当天上线过触发",
    val mailSystemTooltipStatus: String = "<bold>状态：<status>",
    val mailSystemTooltipStatusActivated: String = "已激活",
    val mailSystemTooltipStatusInactivated: String = "未激活",
    val mailTooltipManagementLeft_click: String = "<blora:color:success>左键点击预览",
    val mailTooltipManagementRight_click: String = "<blora:color:error>右键点击切换开启状态",
    val mailViewSender: String = "<bold>发件人：<bold:false><italic><sender>",
    val mailViewTime: String = "<bold>发送时间：<bold:false><italic><date>",
    val mailViewContents: String = "<bold>内容：",
    val mailViewAttachment: String = "<bold>附件：",
    val mailViewAttachment_claimed: String = "<bold>附件（已领取）：",
    val mailErrorNo_permission_to_create_system_mail: String = "你没有创建系统邮件的权限",
    val mailWarningTitle_cannot_be_empty: String = "标题不能为空",
    val mailSuccessCreate_system_mail: String = "成功创建系统邮件 <mail_id>",
    val dialogCreate_system_mailInputTitle: String = "邮件标题",
    val dialogCreate_system_mailInputSystem_sender: String = "系统发件人名称（可选）",
    val dialogCreate_system_mailInputContents: String = "邮件内容",
    val dialogCreate_system_mailButtonCreate: String = "创建",
    val dialogCreate_system_mailButtonCancel: String = "取消",
    val dialogModify_titleTitle: String = "修改邮件标题",
    val dialogModify_system_senderTitle: String = "修改邮件标题",
    val dialogModify_contentsTitle: String = "修改邮件内容",
    val dialogModify_titleInputPlaceholderTitle: String = "标题内容",
    val dialogModify_system_senderInputPlaceholderSystem_sender: String = "系统发送者名称",
    val dialogModify_contentsInputPlaceholderContents: String = "邮件内容",
    val dialogModify_dateModify_online_before_triggerTitle: String = "编辑日期",
    val dialogModify_dateInputPlaceholderYear: String = "年份",
    val dialogModify_dateInputPlaceholderMonth: String = "月份",
    val dialogModify_dateInputPlaceholderDay: String = "日期",
    val dialogModify_datetimeModify_receive_dateTitle: String = "编辑日期",
    val dialogModify_datetimeInputPlaceholderHour: String = "时",
    val dialogModify_datetimeInputPlaceholderMinute: String = "分",
    val dialogModify_datetimeInputPlaceholderSecond: String = "秒",
    val dialogModify_dateWarningYear_must_be_no_negative_digital: String = "年份必须是一个符号为正的<bold>整数<reset>!",
    val dialogModify_dateWarningDay_out_of_limit: String = "日期超过了 <month> 月在 <year> 年的最大天数",
    val dialogModify_daysTitle: String = "修改天数",
    val dialogModify_daysInputPlaceholderDays: String = "天数",
    val dialogModify_amountTitle: String = "修改数量",
    val dialogModify_amountInputPlaceholderAmount: String = "数量",
    val dialogModify_amountWarningMust_be_uint: String = "数量必须是一个正整数",
    val dialogSet_system_mail_identifierTitle: String = "设置邮件 ID",
    val dialogSet_system_mail_identifierWarningIdentifier_exists: String = "当前 ID 已被使用",
    val dialogSet_system_mail_identifierWarningIdentifier_illegal: String = "ID 必须符合如下正则：[a-zA-Z][a-zA-Z0-9_]*",
    val dialogSet_system_mail_identifierInputPlaceholderIdentifier: String = "ID",
    val menuSystem_mail_managementTitle: String = "系统邮件管理",
    val menuMail_listTitle: String = "邮件列表",
    val menuMail_listButtonClaim: String = "领取附件",
    val menuMail_listButtonBack: String = "返回",
    val menuCreate_system_mailTitle: String = "创建系统邮件",
    val menuCreate_system_mailWarningTitle_cannot_be_empty: String = "标题不能为空",
    val menuCreate_system_mailButtonModify_title: String = "修改邮件标题",
    val menuCreate_system_mailButtonModify_system_sender: String = "修改系统发件人名称",
    val menuCreate_system_mailButtonModify_contents: String = "修改邮件内容",
    val menuCreate_system_mailButtonModify_trigger: String = "修改邮件触发器",
    val menuCreate_system_mailButtonModify_attachment: String = "修改邮件附件",
    val menuCreate_system_mailButtonModify_date: String = "修改邮件显示日期",
    val menuCreate_system_mailButtonModify_dateDescriptionNot_set: String = "<italic:false><white>未指定",
    val menuCreate_system_mailButtonModify_dateDescriptionTooltip1: String = "<italic:false><blora:color:success>左键点击修改",
    val menuCreate_system_mailButtonModify_dateDescriptionTooltip2: String = "<italic:false><blora:color:error>右键点击删除",
    val menuCreate_system_mailButtonCreate: String = "创建系统邮件",
    val menuCreate_system_mailPageModify_triggersTitle: String = "修改邮件触发器",
    val menuCreate_system_mailPageModify_triggersButtonDescriptionNot_set: String = "<italic:false><white>未启用该触发器",
    val menuCreate_system_mailPageModify_triggersButtonOnline_before: String = "在指定日期前登录",
    val menuCreate_system_mailPageModify_triggersButtonOnline_beforeDescription: String = "于 <date> 前上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_range: String = "在指定日期区间内登录",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_rangeDescription: String = "于 <from> 至 <to> 期间上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_days: String = "在指定天数内上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_daysDescription: String = "于 <date> 的 <days> 天前之内上线过触发",
    val menuCreate_system_mailPageModify_triggersButtonOnline_in_daysDescription_0days: String = "于 <date> 的当天上线过触发",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeTitle: String = "在指定日期区间内登录",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeButtonModify_from: String = "修改开始日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeButtonModify_to: String = "修改结束日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_rangeWarningFrom_later_than_to: String = "开始日期不能比结束日期更晚",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysTitle: String = "在指定天数内上线过触发",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_anchor: String = "修改锚定日期",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_days: String = "修改天数",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysButtonModify_daysDescription: String = "<italic:false><white><days> 天",
    val menuCreate_system_mailPageModify_triggersSub_pageModify_online_in_recent_daysWarningDays_must_be_non_negative: String = "天数必须是非负整数",
    val menuCreate_system_mailPageModify_attachmentTitle: String = "修改附件",
    val menuCreate_system_mailPageModify_attachmentItemTitle: String = "<italic:false><white>数量 x<amount>",
    val menuCreate_system_mailPageModify_attachmentItemTooltip1: String = "<italic:false><white><bold>名称：",
    val menuCreate_system_mailPageModify_attachmentItemTooltip2: String = "<italic:false><white><bold>描述：",
    val menuCreate_system_mailPageModify_attachmentItemDescription1: String = "<italic:false><blora:color:success>左键点击修改数量",
    val menuCreate_system_mailPageModify_attachmentItemDescription2: String = "<italic:false><blora:color:error>右键点击删除",
    val menuCreate_system_mailPageModify_attachmentCoinTitle: String = "金币",
    val menuCreate_system_mailPageModify_attachmentBloriusTitle: String = "络琅",
    val menuCreate_system_mailPageModify_attachmentCoin_and_bloriusTooltip: String = "<italic:false><white>数量：<amount>",
    val menuCreate_system_mailPageModify_attachmentCoin_and_bloriusDescription2: String = "<italic:false><blora:color:error>右键点击归零",
)

@Serializable
data class RedeemLocalizationContents(
    val redeemNotExists: String = "兑换码不存在",
    val redeemCreate: String = "成功创建兑换码 <redeem>",
    val redeemSuccess: String = "成功创建兑换码 <redeem>，请前往邮箱查看",
    val redeemMailTitle: String = "兑换码奖励",
    val redeemMailSender: String = "百络谷",
    val redeemMailContents: String = "兑换码 <redeem> 的奖励，请注意查收。",
    val redeemTooltipManagementLeft_click: String = "<blora:color:success>左键查看附件",
    val redeemTooltipManagementRight_click: String = "<blora:color:error>右键删除",
    val dialogCreate_redeemTitle: String = "创建兑换码",
    val dialogCreate_redeemWarningExists: String = "兑换码已存在",
    val dialogCreate_redeemWarningName_illegal: String = "兑换码应该只包含字母和数字！（不区分大小写）",
    val dialogCreate_redeemInputPlaceholderRedeem: String = "兑换码",
    val dialogCreate_redeemInputPlaceholderOne_use: String = "是否为一次性兑换码",
    val dialogRedeemTitle: String = "使用兑换码",
    val dialogRedeemWarningNot_exists: String = "兑换码不存在",
    val dialogRedeemWarningRedeemed: String = "您已兑换过该兑换码了",
    val dialogRedeemWarningUsed: String = "该兑换码已被使用",
    val dialogRedeemInputPlaceholderRedeem: String = "兑换码",
    val menuRedeem_code_managementTitle: String = "兑换码管理",
    val menuRedeem_code_managementItemTooltipCreator: String = "<bold>创建者：<creator>",
    val menuRedeem_code_managementItemTooltipCreated_at: String = "<bold>创建于：<date>",
    val menuRedeem_code_managementButtonAdd_new: String = "添加兑换码",
)

@Serializable
data class GuildInviteMenuLocalizationContents(
    val invitationError: String = "当前邀请出现问题",
    val invitationGuild_not_allow_join: String = "<red>当前公会已经设置为无法加入",
    val invitationDescriptionInviter: String = "邀请者：<inviter>",
    val invitationDescriptionInvited_at: String = "邀请于：<invited_at>",
    val invitationDescriptionLeft_click: String = "<green>左键点击同意",
    val invitationDescriptionRight_click: String = "<red>右键点击拒绝",
)

@Serializable
data class GuildMenuLocalizationContents(
    val inviteMenu: GuildInviteMenuLocalizationContents = GuildInviteMenuLocalizationContents(),
    val menuGuildTitle: String = "公会菜单",
    val menuGuildButtonPublic_guilds: String = "公会列表",
    val menuGuildButtonMy_guilds: String = "我的公会",
    val menuGuildButtonInvitation: String = "公会邀请",
    val menuGuildButtonJoin: String = "加入公会",
    val menuGuildButtonCreate: String = "创建公会",
    val menuGuild_inviteTitle: String = "公会邀请",
    val menuGuild_bankTitle: String = "<guild> | 公会银行",
    val menuGuild_bankButtonStore: String = "存入",
    val menuGuild_bankButtonStoreDescription: String = "您当前持有：<amount>",
    val menuGuild_bankButtonStoreWarning: String = "您没有钱可以存入银行了",
    val menuGuild_bankButtonWithdraw: String = "取出",
    val menuGuild_bankButtonWithdrawDescription: String = "当前已存储：<amount>",
    val menuGuild_bankButtonWithdrawWarning: String = "公会银行中的钱不足以取出",
    val menuGuild_invitation_codeTitle: String = "<guild> | 邀请码管理",
    val menuGuild_invitation_codeItemFormat: String = "<italic:false><bold><white><code>",
    val menuGuild_invitation_codeItemDescriptionSingle_use: String = "<italic:false><white>一次性：<single_use>",
    val menuGuild_invitation_codeItemDescriptionCreator: String = "<italic:false><white>创建者：<creator>",
    val menuGuild_invitation_codeItemDescriptionCreated_at: String = "<italic:false><white>创建于：<date>",
    val menuGuild_invitation_codeItemDescriptionExpire_at: String = "<italic:false><white>过期于：<date>",
    val menuGuild_invitation_codeItemDescriptionExpireInfinite: String = "<italic:false><bold><yellow>永不",
    val menuGuild_invitation_codeItemDescriptionRight: String = "<red>右键点击删除",
    val menuGuild_invitation_codeButtonCreate: String = "创建兑换码",
    val menuGuild_viewTitle: String = "<guild>",
    val menuGuild_viewButtonGuild_settings: String = "公会设置",
    val menuGuild_viewButtonRole_management: String = "角色管理",
    val menuGuild_viewButtonMember_list: String = "玩家列表",
    val menuGuild_viewButtonAlly_list: String = "盟友列表",
    val menuGuild_viewButtonInvitation_codes: String = "邀请码",
    val menuGuild_viewButtonInvite_player: String = "邀请玩家", // actually moved to member list
    val menuGuild_viewButtonEnder_chest: String = "公会末影箱",
    val menuGuild_viewButtonBank: String = "公会银行",
    val menuGuild_viewButtonVitality_shop: String = "活跃点商店",
    val menuGuild_viewButtonJoin_guild: String = "申请加入",
    val menuGuild_viewInviteTitle: String = "<guild> | 邀请玩家",
    val menuGuild_member_listTitle: String = "<guild> | 成员列表",
    val menuGuild_member_listMember_managementTitle: String = "<guild> | 成员列表 | <player>",
    val menuGuild_member_listMember_managementRole_managementTitle: String = "<guild> | 成员列表 | <player> | 角色管理",
    val menuGuild_member_listMember_managementRole_managementDescription1: String = "是否拥有角色：<status>",
    val menuGuild_member_listMember_managementRole_managementDescription2: String = "<green>点击切换玩家角色状态",
    val menuGuild_member_listMember_managementButtonTransfer_owner: String = "转让会长",
    val menuGuild_member_listMember_managementButtonModify_roles: String = "修改角色",
    val menuGuild_member_listMember_managementButtonKick: String = "踢出玩家",
    val menuGuild_member_listMember_managementKickTitle: String = "<red>你确定要踢出玩家 <player> 吗？",
    val menuGuild_member_listPlayerDescriptionOwner: String = "<gold><bold>会长",
    val menuGuild_member_listPlayerDescriptionRole: String = "<white>角色：<role>",
    val menuGuild_member_listPlayerDescriptionJoin_at: String = "<white>加入于：<join_at>",
    val menuGuild_member_listPlayerDescriptionError: String = "<red>获取玩家信息时出现错误",
    val menuGuild_member_listButtonJoin_request: String = "加入申请",
    val menuGuild_member_listButtonJoin_requestDescription: String = "<white>当前有 <requests> 个申请待处理",
    val menuGuild_member_listJoin_requestsTitle: String = "<guild> | 成员列表 | 加入申请",
    val menuGuild_member_listJoin_requestsDescriptionAccpet: String = "<green>左键同意",
    val menuGuild_member_listJoin_requestsDescriptionReject: String = "<red>右键拒绝",
    val menuGuild_member_listBlocklistTitle: String = "<guild> | 成员列表 | 黑名单",
    val menuGuild_member_listBlocklistItemDescription: String = "<red>右键移除黑名单",
    val menuGuild_member_listBlocklistButtonAdd: String = "添加黑名单",
    val menuGuild_member_listBlocklistAdd_blockedTitle: String = "<guild> | 成员列表 | 黑名单 | 添加拉黑",
    val menuGuild_role_managementTitle: String = "<guild> | 角色管理",
    val menuGuild_role_managementItemTooltip1: String = "<green>左键点击编辑",
    val menuGuild_role_managementItemTooltip2: String = "<red>右键点击删除",
    val menuGuild_role_managementButtonCreate_role: String = "创建角色",
    val menuGuild_role_managementModify_roleTitle: String = "<guild> | 角色管理 | <role>",
    val menuGuild_role_managementModify_roleButtonModify_name: String = "修改名称",
    val menuGuild_role_managementModify_roleItemAllow: String = "<green>允许",
    val menuGuild_role_managementModify_roleItemDeny: String = "<red>禁止",
    val menuGuild_role_managementModify_roleButtonConfirm: String = "确认修改",
    val menuGuild_settingsTitle: String = "<guild> | 公会设置",
    val menuGuild_settingsModify_iconTitle: String = "<guild> | 修改图标",
    val menuGuild_settingsModify_iconButtonIcon: String = "点击物品栏中的物品更新公会图标",
    val menuGuild_settingsModify_iconButtonConfirm: String = "确认更新",
    val menuGuild_settingsModify_join_strategyTitle: String = "<guild> | 修改加入策略",
    val menuGuild_settingsModify_join_strategySelected: String = "当前选中",
    val menuGuild_settingsModify_join_strategyButtonConfirm: String = "确认更新",
    val menuGuild_listTitle: String = "公会列表",
    val menuGuild_listGuildDescriptionLevel: String = "等级：<guild_level>",
    val menuGuild_listGuildDescriptionOwner: String = "会长：<guild_owner>",
    val menuGuild_listGuildDescriptionCreated_at: String = "创建于：<guild_create_date>",
    val menuGuild_listGuildDescriptionMembers: String = "成员：<guild_members>",
    val menuGuild_listGuildDescriptionVitality: String = "活跃点：<guild_vitality>",
    val menuGuild_listGuildDescriptionJoin_strategy: String = "加入策略：<guild_join_strategy>",
    val menuMy_guildTitle: String = "我的公会",
    val menuCreate_guildTitle: String = "创建公会",
    val menuGuild_settingsButtonModify_id: String = "编辑 ID",
    val menuGuild_settingsButtonModify_display_name: String = "编辑显示名称",
    val menuGuild_settingsButtonModify_icon: String = "编辑图标",
    val menuGuild_settingsButtonModify_visibility: String = "切换可见性",
    val menuGuild_settingsButtonModify_visibilityDescription: String = "可见性：<visibility>",
    val menuGuild_settingsButtonModify_visibilityDescriptionVisible: String = "<green>可见",
    val menuGuild_settingsButtonModify_visibilityDescriptionInvisible: String = "<red>不可见",
    val menuGuild_settingsButtonModify_join_strategy: String = "加入策略",
    val menuGuild_settingsButtonUpgrade: String = "升级公会",
    val menuGuild_settingsButtonUpgradeDescriptionMembers_limit: String = "<white>成员上限：<green><old> 人<white> → <aqua><new> 人",
    val menuGuild_settingsButtonUpgradeDescriptionClaims_limit: String = "<white>领地上限：<green><old> 区块<white> → <aqua><new> 区块",
    val menuGuild_settingsButtonUpgradeDescriptionUpgrade_cost: String = "<yellow>需要消耗活跃点 <cost>",
    val menuGuild_settingsButtonUpgradeDescriptionUpgradable: String = "<green>点击升级",
    val menuGuild_settingsButtonUpgradeDescriptionVitality_not_enough: String = "<red>活跃点不足",
    val menuGuild_settingsButtonDisband_guild: String = "解散公会",
    val menuGuild_settingsButtonModify_join_strategyDescription: String = "当前策略：<strategy>",
    val menuGuild_settingsDisband_guildTitle: String = "<red>你确认要解散公会 <guild> 吗？",
    val menuCreate_guildButtonSet_id: String = "设置 ID",
    val menuCreate_guildButtonModify_display_name: String = "编辑显示名称",
    val menuCreate_guildButtonModify_icon: String = "编辑图标",
    val menuCreate_guildButtonModify_iconTooltip: String = "在物品栏中点击物品设置图标",
    val menuCreate_guildButtonCreate: String = "创建公会",
)

@Serializable
data class GuildDialogLocalizationContents(
    val dialogGuild_bankStoreTitle: String = "存入银行",
    val dialogGuild_bankWithdrawTitle: String = "从银行取出",
    val dialogGuild_bankStoreWarning: String = "您的金额不足你输入的数值",
    val dialogGuild_bankWithdrawWarning: String = "银行中的金额不足您输入的数值",
    val dialogGuild_bankInput: String = "金额",
    val dialogJoin_guildTitle: String = "加入公会",
    val dialogJoin_guildInputCode: String = "邀请码",
    val dialogJoin_guildWarningCode_not_exists: String = "邀请码不存在",
    val dialogJoin_guildWarningIs_member: String = "您已经是该公会的成员了",
    val dialogJoin_guildWarningGuild_reject: String = "该公会当前无法加入",
    val dialogCreate_invitation_codeTitle: String = "创建邀请码",
    val dialogCreate_invitation_codeDescription: String = "当开启“永不过期”后，过期天数的值将被忽略",
    val dialogCreate_invitation_codeInputSingle_use: String = "单次使用",
    val dialogCreate_invitation_codeInputInfinite: String = "永不过期",
    val dialogCreate_invitation_codeInputExpire_days: String = "过期天数",
    val dialogCreate_guildSet_idTitle: String = "设置 ID",
    val dialogCreate_guildSet_idInputPlaceholderId: String = "ID",
    val dialogCreate_guildSet_idWarningId_exists: String = "ID 已存在",
    val dialogCreate_guildSet_idWarningId_illegal: String = "ID 只能由字母和数字组成",
    val dialogCreate_guildSet_idWarningLength: String = "ID 的长度必须大于等于 <min> 且小于等于 <max>",
    val dialogCreate_guildModify_display_nameTitle: String = "编辑显示名称",
    val dialogCreate_guildModify_display_nameInputPlaceholderDisplay_name: String = "显示名称",
    val dialogGuild_settingsModify_idTitle: String = "编辑 ID",
    val dialogGuild_settingsModify_idInputPlaceholderId: String = "ID",
    val dialogGuild_settingsSet_idWarningId_exists: String = "ID 已存在",
    val dialogGuild_settingsSet_idWarningId_illegal: String = "ID 只能由字母和数字组成",
    val dialogGuild_settingsModify_display_nameTitle: String = "编辑显示名称",
    val dialogGuild_settingsModify_display_nameInputPlaceholderDisplay_name: String = "显示名称",
    val dialogGuild_role_managementModify_roleModify_nameTitle: String = "编辑角色名称",
    val dialogGuild_role_managementModify_roleModify_nameInputPlaceholderName: String = "名称",
    val dialogGuild_role_managementCreate_roleTitle: String = "创建角色",
    val dialogGuild_role_managementCreate_roleWarningChars_illegal: String = "角色 ID 只能由小写字母组成且不能为空",
    val dialogGuild_role_managementCreate_roleWarningExists: String = "角色 ID 已存在",
    val dialogGuild_role_managementCreate_roleInputPlaceholderId: String = "角色 ID",
    val dialogGuild_role_managementCreate_roleInputPlaceholderName: String = "角色名称"
)

@Serializable
data class GuildLocalizationContents(
    val menu: GuildMenuLocalizationContents = GuildMenuLocalizationContents(),
    val dialog: GuildDialogLocalizationContents = GuildDialogLocalizationContents(),
    val guildTransfer_ownerAnnouncement: String = "公会 <guild> 的会长已由 <old_owner> 转让给 <new_owner>",
    val guildKick: String = "您已被玩家 <player> 踢出公会 <guild>",
    val guildTransfer_ownerCooldown: String = "转让会长仍在冷却中，剩余 <days> 天",
    val guildBlocklistAdd: String = "已成功将玩家 <player> 列入公会 <guild> 的黑名单",
    val guildBlocklistAdded: String = "你已被列入公会 <guild> 的黑名单",
    val guildBlocklistRemove: String = "已成功将玩家 <player> 从公会 <guild> 的黑名单中移除",
    val guildBlocked: String = "您已被此公会列入黑名单",
    val guildOtherBlocked: String = "该玩家已经被公会列入黑名单",
    val guildBankStore: String = "[公会] <guild>：玩家 <player> 存入了 <amount>",
    val guildBankWithdraw: String = "[公会] <guild>：玩家 <player> 取出了 <amount>",
    val guildBankStoreNo_permission: String = "<red>你没有权限存入银行",
    val guildBankWithdrawNo_permission: String = "<red>你没有权限从银行取出",
    val guildCreateSuccess: String = "成功创建公会 <guild_name>(<guild_id>)",
    val guildJoinAlready_request: String = "<red>您已经申请过了，请等待审核",
    val guildInvite_joinReject: String = "已拒绝 <inviter> 邀请您加入 <guild> 的申请",
    val guildInvite_joinAccept: String = "您同意了 <inviter> 邀请您加入 <guild> 的申请，但仍需要等待公会管理员审核",
    val guildInvitation_code_joinAccept: String = "您使用 <code> 加入 <guild>，但仍需要等待公会管理员审核",
    val guildInvitation_codeCreate: String = "成功创建邀请码 <code>",
    val guildInvitation_codeDelete: String = "成功删除邀请码 <code>",
    val guildJoinRequest_success: String = "已申请加入公会 <guild>",
    val guildJoinSuccess: String = "成功加入公会 <guild>",
    val guildInviteInviter: String = "成功向 <invitee> 发送了加入公会 <guild> 的邀请",
    val guildInviteInvitee: String = "<inviter> 邀请您加入公会 <guild>",
    val guildJoin_requestAnnouncement: String = "玩家 <player> 申请加入您管理的公会 <guild>",
    val guildJoin_requestAccept: String = "您已同意了玩家 <player> 加入公会 <guild> 的申请",
    val guildJoin_requestReject: String = "您已拒绝了玩家 <player> 加入公会 <guild> 的申请",
    val guildJoin_requestAccepted: String = "您加入公会 <guild> 的申请已被同意",
    val guildJoin_requestRejected: String = "您加入公会 <guild> 的申请已被拒绝",
    val guildJoinAnnouncement: String = "玩家 <player> 加入了您所在的公会 <guild>",
    val guildUpgradeVitality_not_enough: String = "<red>活跃点不足",
    val guildUpgradeSuccess: String = "成功升级公会",
    val guildCreateMoney_not_enough: String = "您的络琅不足，创建公会需要 <cost> 络琅",
    val guildJoinLimit: String = "您最多加入 <amount> 个公会",
    val guildCreateLimit: String = "您最多创建 <amount> 个公会",
    val guildDisbandSuccess: String = "成功解散公会 <guild_name>(<guild_id>)",
    val guildDisbandNotify: String = "您所在的公会 <guild_name>(<guild_id>) 已被解散",
    val guildUpdateId: String = "成功更新公会 ID",
    val guildUpdateDisplay_name: String = "成功更新公会名称",
    val guildUpdateIcon: String = "成功更新公会图标",
    val guildUpdateJoin_strategy: String = "成功更新公会加入策略",
    val guildUpdateVisibility: String = "成功更新公会可见性",
    val guildRoleModify_success: String = "成功修改角色 <role>",
    val guildRoleCreate_success: String = "成功创建角色 <role>",
    val guildRoleDelete_success: String = "成功删除角色 <role>",
    val guildRoleUpdate_name: String = "成功修改角色 <role> 的名称",
    val guildRole_permissionModify_guild_name: String = "修改公会名称",
    val guildRole_permissionModify_guild_id: String = "修改公会 ID",
    val guildRole_permissionModify_guild_icon: String = "修改公会图标",
    val guildRole_permissionModify_guild_visibility: String = "修改公会可见性",
    val guildRole_permissionModify_guild_join_strategy: String = "修改公会加入策略",
    val guildRole_permissionKick_player: String = "提出玩家",
    val guildRole_permissionReview_player: String = "审核玩家",
    val guildRole_permissionInvite_player: String = "邀请玩家",
    val guildRole_permissionRequest_ally: String = "请求结盟",
    val guildRole_permissionReview_ally: String = "审核结盟",
    val guildRole_permissionStop_ally: String = "终止结盟",
    val guildRole_permissionManage_invitation_code: String = "管理邀请码",
    val guildRole_permissionStore_bank: String = "向银行存入金币",
    val guildRole_permissionWithdraw_bank: String = "从银行取出金币",
    val guildRole_permissionUse_vitality: String = "使用活跃点",
    val guildJoin_strategyDirect: String = "直接加入",
    val guildJoin_strategyInvite_direct: String = "仅邀请直接加入",
    val guildJoin_strategyRequire_review: String = "需要审核",
    val guildJoin_strategyNot_allow: String = "不允许加入",
    val guildWarningId_cannot_be_empty: String = "ID 不能为空",
    val guildWarningId_exists: String = "ID 已被占用",
    val guildWarningNot_join_any_guilds: String = "<red>您没有加入任何公会",
    val guildWarningNo_permission_to_create: String = "<red>您没有权限创建公会",
)

@Serializable
data class LocalizationContents(
    val command: CommandLocalizationContents = CommandLocalizationContents(),
    val mail: MailLocalizationContents = MailLocalizationContents(),
    val redeem: RedeemLocalizationContents = RedeemLocalizationContents(),
    val guild: GuildLocalizationContents = GuildLocalizationContents(),
    val menuErrorTitle: String = "出现错误，请点击中间的按钮返回上一页",
    val chatMentionTitle: String = "有人在聊天中 @ 了您",
    val chatViewInventory: String = "<viewee> 的背包",
    val chatViewEnderChest: String = "<viewee> 的末影箱",
    val chatViewInventoryTooltip: String = "点击查看",
    val chatViewEnderChestTooltip: String = "点击查看",
    val chatErrorMuted: String = "您已经被禁言",
    val dialogInputBooleanYes: String = "是",
    val dialogInputBooleanNo: String = "否",
    val dialogButtonConfirm: String = "确认",
    val dialogButtonCancel: String = "取消",
    val menuButtonConfirm: String = "确认",
    val menuButtonCancel: String = "取消",
    val menuButtonBack: String = "返回",
    val menuButtonPrevious_page: String = "上一页",
    val menuButtonNext_page: String = "下一页",
    val customPlaceholders: Map<String, String> = mapOf(
        "commandPrefix" to "<dark_gray>[<blora:color:commandPrefix>命令<dark_gray>]<reset> ",
        "managementPrefix" to "<dark_gray>[<blora:color:managementPrefix>管理<dark_gray>]<reset> ",
    ),
    val customColors: Map<String, String> = mapOf(
        "success" to "211, 218, 196",
        "error" to "156, 88, 62",
        "commandPrefix" to "156, 169, 134",
        "managementPrefix" to "171, 170, 120",
        "primary" to "187, 184, 185",
        "primaryHighlight" to "225, 218, 211"
    ),
) {

    fun resolver(): TagResolver {
        return LocalizationsTagResolver(
            this.customPlaceholders.toMap(),
            this.customColors.toMap()
        )
    }

}