name: Blora
main: blora.plugin.BloraPlugin
version: "1.0.0"
api-version: "1.19"
bootstrapper: blora.plugin.BloraBootstrap
loader: blora.plugin.library.BloraLibraryLoader

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      join-classpath: true
      required: false
    CraftEngine:
      load: BEFORE
      join-classpath: true
      required: false
    PlayerPoints:
      load: BEFORE
      join-classpath: true
      required: false
    Vault:
      load: BEFORE
      join-classpath: true
      required: false
    XConomy:
      load: BEFORE
      join-classpath: true
      required: false
    Aurora:
      load: BEFORE
      join-classpath: true
      required: false
    AuroraLevels:
      load: BEFORE
      join-classpath: true
      required: false